apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: conversaopeso
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: epinheiro/conversaopeso:v1
          ports:
            - containerPort: 80

---
# Service para expor a aplicação web
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80 # Porta do container web
      nodePort: 30000 # Porta do serviço
  type: NodePort